### PR TITLE
Fix/ticket73

### LINKED ISSUE #73: [BUG] deleted files still show in my workspace
I did a clone to download all of `devs.near`'s widgets. 

(from /examples, see [contributing guide](https://github.com/NEARBuilders/bos-workspace/tree/main/examples))
`../bin/bw.js clone devs.near`

I checked them out locally

`../bin/bw.js ws dev`

They appeared. I went through and deleted a ton because I don't need all these widgets.

I run them again...
`../bin/bw.js ws dev`

but these files are still showing in bos-workspace portal, despite not in my filesystem.

After deleting files, they should no longer show in my workspace.

### PR DESCRIPTION
**Pull request by itechunter**
Resolves #73

### CODE REVIEW

File: lib/build.ts [hunk 1]
```diff
@@ -121,20 +127,35 @@ export async function buildApp(src: string, dest: string, network: string = "mai
...
     }
+
     loadingWidgets.finish(`Transpiled ${widgets.length} widgets`);
   } catch (e) {
     loadingWidgets.error(`Failed to transpile widgets`);
     throw e;
   }
 
+  // remove unnecessary build files
+  await loopThroughFiles(path.join(dest, "src", "widget"), async (file: string) => {
```
Comment (elliotBraem) [inline lib/build.ts:149]: Can you write a test in[test/unit/build.ts](https://github.com/NEARBuilders/bos-workspace/blob/main/tests/unit/build.ts)

'should remove unnecessary files from build on rebuild`

**Review by elliotBraem — APPROVED** [review]
